name: Daily YouTube Music Playlist Update

on:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ytmusicapi python-dotenv

    - name: Run Python script
      id: run_script
      env:
        OAUTH_JSON_BASE64: ${{ secrets.OAUTH_JSON_BASE64 }}
        PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
      run: |
        python YouTube.py

    - name: Update OAuth Secret
      uses: punitkashyup/action-secrets-update@v1.0.6
      with:
        repository_owner: ${{ github.repository_owner }}
        repository_name: ${{ github.event.repository.name }}
        secret_name: OAUTH_JSON_BASE64
        new_secret_value: ${{ steps.run_script.outputs.OAUTH_JSON_BASE64 }}
        github_token: ${{ secrets.PAT }}
